name: my first workflow attempt

'on':
  push:
  workflow_dispatch:

jobs:
  my-job:
    needs:
      - another-job
    env:
      pluto: 'paperino'
    runs-on: ubuntu-latest
    steps:
      - run: |
          pluto=pippo
          echo "I'm" $pluto running on ${{ runner.os == 'Linux' }}
          echo ${{ env.pluto }}
        name: "Print the $pluto OS name: ${{ runner.os }}"
      - name: Install tree
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Watch the tree
        run: tree -a
      - name: Print the other random
        run: echo ${{ needs.another-job.outputs.random }}
  another-job:
    runs-on: windows-latest
    outputs:
      random: ${{ steps.randomgen.outputs.random }}
    steps:
      - shell: bash
        name: Print the OS name
        run: |
          echo this is
          echo a multiline run step
          echo running on ${{ runner.os }}
      - run: echo end
      - shell: bash
        name: compute a random number
        id: randomgen
        run: |
          ruby -e 'puts "::set-output name=random::#{rand(1..6)}"'
      - shell: bash
        name: print the previous random
        if: steps.randomgen.outputs.random > 3
        env:
          MY_RANDOM: ${{ steps.randomgen.outputs.random }}
        run: |
          echo ${{ steps.randomgen.outputs.random }}
          echo from variable: $MY_RANDOM
