name: my first workflow attempt

'on':
  push:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo I'm running on ${{ runner.os }}
  another-job:
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          echo this is
          echo a multiline run step
          echo running on ${{ runner.os }}
      - run: echo end
