name: my first workflow attempt

'on':
  push:
  workflow_dispatch:

jobs:
  my-job:
    env:
      pluto: 'paperino'
    runs-on: ubuntu-latest
    steps:
      - run: |
          pluto=pippo
          echo "I'm" $pluto running on ${{ runner.os == 'Linux' }}
          echo ${{ env.pluto }}
        name: "Print the $pluto OS name: ${{ runner.os }}"
      - name: Install tree
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Watch the tree
        run: tree -a
  another-job:
    runs-on: windows-latest
    steps:
      - shell: bash
        name: Print the OS name
        run: |
          echo this is
          echo a multiline run step
          echo running on ${{ runner.os }}
      - run: echo end
